colcon_bundle/verb/assets/setup.sh
Change the order of PATH to search executable in usr/bin prior to usr/local/bin
=> Change the order of defined PATH

colcon_bundle/installer/pip.py, colcon_bundle/installer/pip3.py, test/test_pip_installer.py
Adds --pip-args and --pip3-args which behave exactly like --cmake-args in the colcon-cmake package. When used, the arguments are passed directly to pip/pip3. This will allow users to use arguments like '--index-url' to install from custom Python repositories.
=> Add --pip-args and --pip3-args

colcon_bundle/installer/base_pip_installer.py, test/test_pip3_installer.py, test/test_pip_installer.py
This is similar logic to how the apt installer chooses not to run. This should save time when pip dependencies aren't changing.
=> Update pip installer to not install if dependencies didn't change

colcon_bundle/installer/assets/apt_package_blacklist.txt
libignition-* needed by Gazebo9 are preinstalled with the simulator.
Blacklisting them should not affect so long Gazebo9 is installed as
these packages are dependency of Gazebo9. However not blacklisting
causes the bundle to fail during execution as the current version in
ubuntu repo is outdated and not compatible with latest version of
Gazebo9.
Error seen while running with outdated version of these packages
with new version of Gazebo9:
```
/opt/amazon/RoboMakerGazebo/bin/gzserver: symbol lookup error:
/opt/amazon/RoboMakerGazebo/lib/libgazebo_common.so.9: undefined symbol:
_ZN8ignition10fuel_tools12ClientConfig12SetUserAgentERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
gzclient: symbol lookup error:
/opt/amazon/RoboMakerGazebo/lib/libgazebo_common.so.9: undefined symbol: …
```
=> Addition of ignition packages to blacklist

BUNDLE_FORMAT.md
**overlays.json** example is missing commas "," in 2 places, after the sha256 values. This change adds the commas so that it validates as JSON correctly.
=> Fix BUNDLE_FORMAT.md's overlays.json to valid JSON

BUNDLE_FORMAT.md, colcon_bundle/verb/bundlefile.py, test/test_bundlefile.py
Tar files write in 512 byte blocks. I was not taking that into account when computing the offset of subsequent overlays.
https://www.gnu.org/software/tar/manual/html_node/Blocking.html
=> Fix offset metadata of overlays

Dockerfile, colcon_bundle/__init__.py, setup.cfg, test/test_setup.py
If we don't fix this then customers get this error when they have colcon-core of a later version:
```
Starting >>> deepracer_msgs
]0;colcon build [0/4 done] [1 ongoing]Starting >>> deepracer_simulation
]0;colcon build [0/4 done] [2 ongoing]Finished <<< deepracer_simulation [11.0s]
]0;colcon build [1/4 done] [1 ongoing]Starting >>> sagemaker_rl_agent
]0;colcon build [1/4 done] [2 ongoing]Finished <<< sagemaker_rl_agent [1.31s]
]0;colcon build [2/4 done] [1 ongoing]Finished <<< deepracer_msgs [12.5s]
]0;colcon build [3/4 done] [0 ongoing]Starting >>> deepracer_interpreter
]0;colcon build [3/4 done] [1 ongoing]Finished <<< deepracer_interpreter [23.6s]
]0;colcon build [4/4 done] [0 ongoing]
Summary: 4 packages finished [36.7s]
1 package had stderr output: sagemaker_rl_agent …
```
=> Update colcon-core dependency

setup.cfg
Following Dirk's lead on the changelog:
https://github.com/colcon/colcon-core/blob/master/setup.cfg#L5
https://github.com/colcon/colcon.readthedocs.org/pull/42/files
=> Add project urls to setup.cfg

colcon_bundle/verb/_archive_generators.py, colcon_bundle/verb/bundle.py, colcon_bundle/verb/bundlepath.py, colcon_bundle/verb/pathcontext.py
Add dependency hash check during bundling and save bundle time if dependencies have not changed.
**Testing**
pytest unittest
integration test
functional test:
1. build v2 bundle against test_workspace for the first time (~15 minutes)
1. build again and it takes 40 seconds to build since the hash matches
1. change the order of the dependencies in the package.xml, build again, and it takes the same 40 seconds since the hash matches
1. add 'roscpp' as exec dependency in the test-cmake/package.xml and build. Hash mismatch and it takes 4 minutes to build
1. build again and it takes 40 seconds since hash matches 
New commit: [e899841](https://github.com/colcon/colcon-bundle/commit/e899841e43a5fb08d19e9667759a258abecfb007)
1. Check dependencies.tar.gz existence before checking dependencies hash …
=> Add dependency hash check during bundling

colcon_bundle/installer/assets/xenial.sources.list, colcon_bundle/installer/base_pip_installer.py
If the user has a local python site and installed editable packages,
they will appear in the output of `pip freeze` in a different format
than other installed packages.
Tested on Ubuntu as normal user with an editable copy of `colcon-bundle` installed.  `colcon bundle` succeeds in my catkin workspace.
=> Do not look for version number on editable pip packages

Dockerfile.melodic, colcon_bundle/installer/apt.py
Creating the apt cache affects the config values. To find the
correct key paths, we get the value before creating the cache.
```
In [1]: import apt
In [2]: apt.apt_pkg.config.find_file('Dir::Etc::trusted')
Out[2]: '/etc/apt/trusted.gpg'
In [3]: cache = apt.Cache(rootdir='/workspace/aptcache')
In [4]: apt.apt_pkg.config.find_file('Dir::Etc::trusted')
Out[4]: '/workspace/aptcache/etc/apt/trusted.gpg'
```
=> Support Melodic, fix aptitude trusted key config

Dockerfile.backwards, Dockerfile.kinetic, Dockerfile.melodic
This fixes the failing integration tests until the container images are updated in dockerhub.
=> Add new key to Dockerfiles

colcon_bundle/verb/_installer_manager.py
This if statement was missed in the refactor. It causes an empty `sources.tar.gz` to be created in the bundle directory even if `--include-sources` is not supplied.
=> Don't create sources.tar.gz unless --include-sources

Dockerfile.dashing
`colcon-ros-bundle` ROS2 support is pushed, we should use master branch.
=> Update ROS2 test to use colcon-ros-bundle master

colcon_bundle/task/python/bundle.py
We currently don't install unversioned pip dependencies. We should install them properly as versions are not required.
=> Support unversioned python dependencies

colcon_bundle/installer/apt.py, test/__init__.py, test/installer/test_apt_installer.py
As apt is capable of using versions of packages, it would be great to have the same capability in colcon. Just as you could install any apt package by "apt install <package>=<version>", this could be defined in a corresponding rosdep.yaml  and therefore here as well.
=> Support the versioning system from apt

colcon_bundle/installer/base_pip_installer.py, test/installer/test_pip3_installer.py, test/installer/test_pip_installer.py
From [this issue](https://github.com/pypa/virtualenv/issues/1493) it looks like `setuptools` after version 45 breaks python 2 builds.
Change the pip install to target setup tools version 44 only.
=> Limit setuptools to version 44

.github/workflows/test.yml, DEVELOPMENT.md, run_integration_test.sh, run_ros2_integration_test.sh
Ports over all the tests from Travis CI to Github Actions.
Runs every morning PST.
Example of this running is in #128.
Addresses ros-security/aws-roadmap#169
`-it` flags were removed because we do not require an interactive terminal for the `docker run` commands and an interactive terminal is not available on the hosts running the GH actions.
The version of `setuptools` was set to `44.0.0` to avoid python2/3 compatibility issues (See #127).
Signed-off-by: Anas Abou Allaban allabana@amazon.com
=> Port Travis CI to Github Actions

README.md
Add the new Github action workflow badge to the README.
=> Add GH Action badge to README

.github/workflows/test.yml
Disable AWS configuration on tasks triggered by PRs.
This will allow PRs ran from forks (that do not include AWS credentials) to run CI.
Signed-off-by: Zachary Michaels <zmichaels11@gmail.com>
=> Only run Configure AWS Credentials on schedule

colcon_bundle/verb/utilities.py, test/assets/template_shebang.sh, test/test_utilities.py
Make the shebang update stricter and handle new cases with spaces and templates
Examples:
```
#! /usr/bin/python -> #!/usr/bin/env python
#!@PYTHON_EXECUTABLE@ -> #!@PYTHON_EXECUTABLE@ 
```
=> Make shebang update stricter and handle more cases

colcon_bundle/verb/bundlefile.py, test/test_bundlefile.py
Fixes https://github.com/colcon/colcon-bundle/issues/160
```bash
➜ python3.8 -m pytest -v test/test_bundlefile.py
==================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.8.2, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3.8
cachedir: .pytest_cache
inifile: setup.cfg
plugins: cov-2.8.1, repeat-0.8.0, rerunfailures-9.0, mock-1.7.1
collected 2 items
test/test_bundlefile.py::TestBundlefile::test_bundlefile PASSED …
```
=> Fix broken test_bundlefile.py for py3.8

requirements_devel.txt, setup.cfg
The `CHANGELOG.md` for `distro` indicates that there were no changes related to Linux between 1.2.0 and 1.3.0.
Moving to 1.2.0 will make the package installable on RHEL 7 with no adverse side effects.
Here is the `distro` changelog: https://github.com/nir0s/distro/blob/v1.3.0/CHANGELOG.md#130-20180509
This dependency was originally introduced by [#21](https://github.com/colcon/colcon-bundle/pull/21/files#diff-e87397d755f3cab2259647c5e8dbdbe4)
=> Relax the distro requirement from 1.3.0 to 1.2.0

colcon_bundle/installer/__init__.py
Fix issue causing tox to error in CI.
See: https://github.com/colcon/colcon-bundle/runs/671763965?check_suite_focus=true
Signed-off-by: Zachary Michaels <zmichaels11@gmail.com>
=> Specify the formatting explicitly to avoid missing placeholder error

colcon_bundle/installer/apt.py
Install python-pip for distros other than focal
=>  Fix support for `--pip-requirements`

colcon_bundle/installer/assets/bionic.sources.list, colcon_bundle/installer/assets/focal.sources.list, colcon_bundle/installer/assets/xenial.sources.list
Use the `mirror` protocol so `apt` selects the best mirror to use for downloading packages.
The default `sources.list` file used by colcon-bundle hardcoded the repo to the US mirror.
`apt` will now select the best mirror based on network and location.
Using the US repo on an instance in Tokyo, `colcon bundle` took 14m 59.416s.
Using the `mirror` protocol, bundling now takes 3m 47.402s
The mirror protocol does not work for Ubuntu Xenial (16.04) so we use the default archive repo instead of the explicit one from the US (which redirects to it's own mirror accordingly).
=> Use ubuntu mirrors package for debian sources.list

Dockerfile.backwards, Dockerfile.dashing, Dockerfile.double, Dockerfile.kinetic, Dockerfile.melodic, setup.cfg
The setup.cfg was causing the dockerfile to still install setuptools 50 in `pip3 install colcon-bundle`. I think this line is using the local directory, not pypi, so this should fix CI. Followup to #179
=> Use distutils workaround for latest setuptools v50

.github/workflows/test_bundle.repos
The integration tests were failing due to a bug in `perception_pcl` where the library is not at the expected install location, caused by https://github.com/ros-perception/perception_pcl/issues/318.
This change is a workaround that adds `perception_pcl` to the workspace so it builds from source.
The commit pinned for `perception_pcl` is [HEAD of kinetic-devel](https://github.com/ros-perception/perception_pcl/commit/539b5a78b2fb0f0004911c8f85d43a3cc0472625)
Signed-off-by: Zachary Michaels <zacmicha@amazon.com>
=> Add perception_pcl to test_bundle.repos to fix integration tests

colcon_bundle/verb/assets/v1_setup.sh, colcon_bundle/verb/assets/v2_setup.sh
Adding paths for ROS1 Noetic and ROS2 Foxy in the setup.sh file that is generated for sourcing the dependency overlay.
=> Add support for ROS1 Noetic and ROS2 Foxy in setup.sh files.

colcon_bundle/verb/_archive_generators.py, colcon_bundle/verb/_path_context.py
For bundle v2, it is possible that a broken bundle can be produced if the previous run did not succeed because the old cache is loaded. 
This change adds a `.valid` file to the bundle cache after a v2 bundle is created.
On subsequent builds:
* if the `.valid` file exists: it is removed so this current build's cache will not be used if it fails to bundle.
* if the `.valid` file does not exist: the cache is cleared
Signed-off-by: Zachary Michaels <zacmicha@amazon.com>
=> Delete cache if the bundle operation did not succeed.

test/installer/test_apt_installer.py
These two tests will fail if run on a non-Ubuntu distribution. It is simple enough to just skip them so that the other tests in the file can still be run.
=> Skip tests requiring debian on other platforms

Dockerfile.backwards, colcon_bundle/installer/base_pip_installer.py, test/installer/test_pip3_installer.py, test/installer/test_pip_installer.py
Force pip to stay on 20.x version.
This PR also removes a portion of the backwards compatibility integration test that relies on pip installing the latest version of colcon, which will cause the integration test to fail since it will upgrade pip to v21.
See https://pip.pypa.io/en/stable/news/#id1 release notes for v21.0, which states that support for python 3.5 is dropped.
See https://github.com/pypa/pip/issues/9515 for some more information
Similar fixes:
https://github.com/ros-tooling/setup-ros-docker/pull/39
https://github.com/ros-tooling/setup-ros/pull/337
Signed-off-by: Jesse Ikawa <jikawa@amazon.com>
=> Prevent pip from upgrading to v21 for Xenial

Dockerfile.backwards, Dockerfile.dashing, Dockerfile.double, Dockerfile.foxy, Dockerfile.melodic
Add command to docker files to update the expired OSRF gpg key.
ROS Discourse post regarding the gpg expiration incident:
https://discourse.ros.org/t/ros-gpg-key-expiration-incident/20669/27
Signed-off-by: Jesse Ikawa <jikawa@amazon.com>
=> Update expired OSRF gpg key

.github/workflows/test.yml
* GitHub Actions workflows are failing because cached python3.5 versions have been removed from x86 runners
* More details in https://github.com/actions/virtual-environments/issues/4744
* Failure stack trace:
```
Run actions/setup-python@v1
with:
python-version: 3.5
architecture: x64
env:
TOXENV: unittest
Error: Version 3.5 with arch x64 not found
```
* Bump `actions/setup-python` to latest version v2 to allow it to setup pyhton3.5 successfully
Signed-off-by: Prajakta Gokhale <prajaktg@amazon.com>
=> Bump actions/setup-python to v2

setup.cfg
```
/usr/lib/python3.11/site-packages/setuptools/config/expand.py:142: UserWarning: File 'src/colcon-bundle/README.rst' cannot be found
warnings.warn(f"File {path!r} cannot be found")
```
=> Fix long_description file name for README.md
