colcon/colcon-bundle

colcon_bundle/verb/_utilities.py

This might fix the pip3 rosversion issue.

Handle python shebangs with full path

---

colcon_bundle/installer/apt.py

Allow users to utilize their own apt sources list by providing the --apt-sources-list argument. This will completely override the default sources we include with this package.

Add --apt-sources-list to allow overriding apt sources

---

colcon_bundle/verb/assets/setup.sh

This caused ARM libraries to be loaded improperly

Fix typo in arm locations of LD_LIBRARY_PATH

---

colcon_bundle/verb/bundle.py
setup.cfg

Method signature changed in 0.3.15.

Fix update_object calls for colcon-core 0.3.15

---

colcon_bundle/verb/utilities.py

Minor fixes I've found as I work with other ROS setups.

Update catkin rewrites to include 10.ros.sh. Exclude .so files from shebang updates.

---

colcon_bundle/installer/assets/xenial.sources.list

Contains additional Gazebo packages

Add OSRF repo to Xenial sources list. 

---

colcon_bundle/verb/bundle.py

Add error message when no packages are discovered

---

colcon_bundle/verb/__init__.py
colcon_bundle/verb/bundle.py

Add a check for the bundle version

---

colcon_bundle/verb/_archive_generators.py
colcon_bundle/verb/bundlefile.py

Add logging to bundle creation code path

---

colcon_bundle/installer/apt.py

Fix python-apt installation error reporting

---

.travis.yml
Dockerfile.double
colcon_bundle/verb/_path_context.py

We need the exist_ok=true when creating the cache because it is allowed to exist.

Fix error when bundling multiple times

---

colcon_bundle/installer/assets/bionic.sources.list
colcon_bundle/installer/assets/xenial.sources.list

Add arm64 to sources.list

---

requirements_devel.txt
setup.cfg
test/installer/test_apt_installer.py

Crossing the streams seems to yield strange behavior: https://stackoverflow.com/a/50586544/4490656
I was reproducing that behavior with:
- python 3.6.8
- pytest 2.9.2
- mock 2.0.0

Use only a single mock framework

---

colcon_bundle/verb/_overlay_utilities.py
colcon_bundle/verb/utilities.py
integration/test_ros2_v2.sh
setup.cfg
test/assets/dummy_ws/opt/built_workspace/local_setup.sh
test/assets/dummy_ws/opt/built_workspace/local_setup_expected.sh
test/test_utilities.py

Temporary workaround for ROS2 support.
Related: https://github.com/colcon/colcon-ros/issues/67

Patch local_setup.sh to set AMENT_CURRENT_PREFIX

---

integration/test_workspace/src/test-pip-install/package.xml
integration/test_workspace/src/test-pip-install/src/test-pip-install.py

Swap out pyquaternarion for another simple Python package since pyquaternarion is failing to rosdep install.

Fix pip install integration test

---

colcon_bundle/verb/bundlefile.py

This should fix https://github.com/colcon/colcon-bundle/issues/86

Set tarfile.DEFAULT_FORMAT when generating bundle

---

colcon_bundle/installer/__init__.py
colcon_bundle/verb/bundle.py

* https://github.com/colcon/colcon-bundle/issues/124
* https://github.com/ros-security/aws-oncall/issues/23
Signed-off-by: Zachary Michaels <zmichaels11@gmail.com>

Change mood to imperative

---

.github/workflows/test.yml

* Add the CW Metrics GH Action to the testing workflow.
See the unit test job of #136 for an example of a successful run and #135 for an example of a failed run.
Signed-off-by: Anas Abou Allaban <aabouallaban@pm.me>

Add metrics logging to workflow

---

colcon_bundle/verb/utilities.py
test/assets/regular_node_shebang_expected.sh
test/assets/regular_python3_shebang_expected.sh
test/assets/regular_python_shebang_expected.sh

Remove comment that shebang has been modified.

Remove shebang comment

---

colcon_bundle/verb/_path_context.py

As per https://github.com/ros-infrastructure/rep/pull/256

Respect ignore marker even if dangling symlink

---

.github/workflows/test.yml

Signed-off-by: Prajakta Gokhale <prajaktg@amazon.com>

Bump action-cloudwatch-metrics to latest version

---

.github/workflows/test.yml

Run tests hourly.
Follow the pattern of other packages' CI for consistency.

Run tests hourly

---

colcon_bundle/installer/apt.py
colcon_bundle/installer/assets/focal.sources.list
colcon_bundle/verb/utilities.py

This PR supports Ubuntu20.04 and ROS Noetic.
https://github.com/colcon/colcon-bundle/issues/168

to support focal and noetic

---

colcon_bundle/__init__.py
test/test_setup.py

Signed-off-by: Emerson Knapp <eknapp@amazon.com>

Bump to version 0.0.21 for release

---

colcon_bundle/__init__.py
test/test_setup.py

Bump version to 0.0.22 for release

---

Dockerfile.backwards
Dockerfile.dashing
Dockerfile.double
Dockerfile.kinetic
Dockerfile.melodic

It seems that setuptools might be broken (https://github.com/pypa/setuptools/issues/2356) in the latest version, trying out disabling its use

Block using setuptools 50

---

.github/workflows/test.yml

Add test action when pushing to master

---

colcon_bundle/installer/apt.py

Add Retries to apt config

---

.github/workflows/test_bundle.repos

This adds a repos file needed by #188 

Add test bundle repos file

---

colcon_bundle/verb/assets/v1_setup.sh
colcon_bundle/verb/assets/v2_setup.sh

Fixing Issue #192 by adding arm64 paths to the LD_LIBRARY_PATH

Fix LD_LIBRARY_PATH for ARM64 systems

---

.github/workflows/test_bundle.yml

Fix CI builds by updating to latest versions

Update action-ros-ci to 0.1.0

---

colcon_bundle/__init__.py
test/test_setup.py

Signed-off-by: Jesse Ikawa <jikawa@amazon.com>

Bump version to 0.1.1

---

colcon_bundle/verb/_overlay_utilities.py

Make changes to the template's copy rather than the template in asset folder to avoid permission issues.
This issue can be reproduced by sudo pip installing colcon-bundle 0.1.0 or 0.1.1, then attempting to run colcon bundle without sudo. It will show the following error:
```
Creating bundle archive V2...
[167.466s] ERROR:colcon:colcon bundle: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/colcon_bundle/verb/assets/v2_workspace_setup.bash'
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/colcon_core/command.py", line 528, in verb_main
rc = context.args.main(context=context)
File "/usr/local/lib/python3.6/dist-packages/colcon_bundle/verb/bundle.py", line 143, in main
dependencies_changed)
File …
```

Make template changes after copy

---

colcon_bundle/__init__.py
test/test_setup.py

Signed-off-by: Jesse Ikawa <jikawa@amazon.com>

Bump version to 0.1.2

---

.github/workflows/test.yml
Dockerfile.foxy
integration/ros2_workspace/src/test_py_module/setup.py
run_integration_test.sh
run_ros2_integration_test.sh

Most of the foxy changes were already made. This commit adds an integration test for foxy that matches the testing done on dashing.

Add foxy integration test
